[package]
name = "ProjectKnow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.4.2"
walkdir = "2"
dot-writer = "0.1.2"
clap = { version = "3.1.10", features = ["derive", "cargo"] }

